version: '3.8'

services:
  rsnapshot:
    image: wertbon1789/rsnapshot-alpine:1.0.0
    container_name: rsnapshot
    build:
      context: ./build
      dockerfile: ./Dockerfile
    volumes:
      - "./rsnapshot.conf:/etc/rsnapshot.conf"
      - "./crontab:/crontab:ro"
      #- "<your_snapshot_root_here>:/snapshots"
      #- "<your_backup_data_here>:/data"
