version: '3.8'

services:
  rsnapshot:
    image: rsnapshot-alpine:0.0.1
    container_name: rsnapshot
    build:
      context: ./build
      dockerfile: ./Dockerfile
    volumes:
      - "./rsnapshot.conf:/etc/rsnapshot.conf"